package com.honeyapps.wordlebattles.ui.theme

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

data class Dimens(
    val appImage: Dp,
    val animatedIcon: Dp,
    val backspaceHeight: Dp,
    val backspaceWidth: Dp,
    val borderXS: Dp,
    val circleShape: Dp,
    val dividerS: Dp,
    val dividerM: Dp,
    val flagS: Int,
    val flagM: Int,
    val flagL: Int,
    val fontS: TextUnit,
    val fontM: TextUnit,
//    val fontL: TextUnit,
    val fontXL: TextUnit,
    val fontXXL: TextUnit,
    val keyHeight: Dp,
    val keyWidth: Dp,
    val konfetti: Int,
    val iconS: Dp,
    val photoS: Dp,
    val photoM: Dp,
    val photoL: Dp,
    val paddingEmptyContent: Dp,
    val paddingXXS: Dp,
    val paddingXS: Dp,
    val paddingS: Dp,
    val paddingM: Dp,
    val paddingL: Dp,
    val paddingXL: Dp,
    val spacerXXS: Dp,
    val spacerXS: Dp,
    val spacerS: Dp,
    val spacerMS: Dp,
    val spacerM: Dp,
    val spacerML: Dp,
    val spacerL: Dp,
    val spacerXL: Dp,
    val spacerXXL: Dp,
    val squareShape: Dp,
)

val dimens = Dimens(
    appImage = 150.dp,
    animatedIcon = 64.dp,
    backspaceHeight = 28.dp,
    backspaceWidth = 64.dp,
    borderXS = 1.dp,
    circleShape = 36.dp,
    dividerS = 1.dp,
    dividerM = 5.dp,
    flagS = 48,
    flagM = 96,
    flagL = 144,
    fontS = 16.sp,
    fontM = 20.sp,
//    fontL = 24.sp,
    fontXL = 28.sp,
    fontXXL = 32.sp,
    keyHeight = 36.dp,
    keyWidth = 22.dp,
    konfetti = 12,
    iconS = 24.dp,
    photoS = 32.dp,
    photoM = 64.dp,
    photoL = 96.dp,
    paddingEmptyContent = 104.dp,
    paddingXXS = 2.dp,
    paddingXS = 4.dp,
    paddingS = 8.dp,
    paddingM = 12.dp,
    paddingL = 16.dp,
    paddingXL = 20.dp,
    spacerXXS = 2.dp,
    spacerXS = 4.dp,
    spacerS = 8.dp,
    spacerMS = 12.dp,
    spacerM = 16.dp,
    spacerML = 20.dp,
    spacerL = 24.dp,
    spacerXL = 28.dp,
    spacerXXL = 32.dp,
    squareShape = 44.dp,
)